#!/usr/bin/env python3
"""
Convert assets/source/anchor_logo.png to an LVGL 8.4 RGB565 image
descriptor at assets/generated/anchor_logo_<size>.c.

Author:  Colin Bitterfield <colin@bitterfield.com>
License: Proprietary

Usage:   python3 convert_logo.py [size]
Default size is 140 (px square). Output format matches LVGL 8.4's
LV_IMG_CF_TRUE_COLOR with two-byte RGB565 little-endian pixels,
which is what `LV_COLOR_DEPTH 16` + the standard flush callback
expect on this build.

Re-run after replacing source/anchor_logo.png if you want to ship
a different brand logo (per the [[brand]] config story in the
issue spec).
"""

import os
import sys
from PIL import Image

HERE   = os.path.dirname(os.path.abspath(__file__))
SRC    = os.path.join(HERE, "source", "anchor_logo.png")
OUTDIR = os.path.join(HERE, "generated")

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert(size: int):
    im = Image.open(SRC).convert("RGB")
    if im.size != (size, size):
        im = im.resize((size, size), Image.LANCZOS)
    sym = f"anchor_logo_{size}"
    c_path = os.path.join(OUTDIR, f"{sym}.c")
    os.makedirs(OUTDIR, exist_ok=True)

    px = im.load()
    bytes_per_pixel = 2
    total_bytes = size * size * bytes_per_pixel

    with open(c_path, "w") as fh:
        fh.write(f"""/*
 * Auto-generated by assets/convert_logo.py from
 * assets/source/anchor_logo.png at {size}x{size} (RGB565, LE).
 *
 * DO NOT EDIT BY HAND — regenerate via:
 *     python3 assets/convert_logo.py {size}
 *
 * Author:  Colin Bitterfield <colin@bitterfield.com>
 * License: Proprietary
 */

#include "lvgl.h"

static const uint8_t {sym}_map[] = {{
""")
        line_pixels = 16
        i = 0
        for y in range(size):
            for x in range(size):
                r, g, b = px[x, y]
                v = rgb565(r, g, b)
                lo = v & 0xFF
                hi = (v >> 8) & 0xFF
                fh.write(f"0x{lo:02x},0x{hi:02x},")
                i += 1
                if i % line_pixels == 0:
                    fh.write("\n")
        fh.write(f"""
}};

const lv_img_dsc_t {sym} = {{
    .header.cf       = LV_IMG_CF_TRUE_COLOR,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w        = {size},
    .header.h        = {size},
    .data_size       = {total_bytes},
    .data            = {sym}_map,
}};
""")
    print(f"wrote {c_path} ({total_bytes} bytes pixel data)")

if __name__ == "__main__":
    sizes = [int(a) for a in sys.argv[1:]] or [140]
    for s in sizes:
        convert(s)
